export const students = JSON.stringify({
  response: {
    students: [
      {
        city: 'Fushë-Muhurr',
        company: 'Yadel',
        email: 'email-with-one-result',
        firstName: 'Ingaberg',
        grades: ['78', '100', '92', '86', '89', '88', '91', '87'],
        id: '1',
        lastName: 'Orton',
        pic: 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/voluptasdictablanditiis.jpg',
        skill: 'Oracle',
      },
      {
        city: 'Sanghan',
        company: 'Avamm',
        email: 'email-with-two-results',
        firstName: 'Clarke',
        grades: ['75', '89', '95', '93', '99', '82', '89', '76'],
        id: '2',
        lastName: 'Boards',
        pic: 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/voluptasautreprehenderit.jpg',
        skill: 'Sports',
      },
      {
        city: 'Kugesi',
        company: 'Skalith',
        email: 'email-with-two-results',
        firstName: 'Laurens',
        grades: ['88', '90', '79', '82', '81', '99', '94', '73'],
        id: '3',
        lastName: 'Romanet',
        pic: 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/aspernaturnonsapiente.jpg',
        skill: 'Employee Handbooks',
      },
      {
        city: 'Krajan',
        company: 'Mybuzz',
        email: 'bskitt3@aboutads.info',
        firstName: 'Berti',
        grades: ['88', '93', '92', '81', '95', '98', '77', '94'],
        id: '4',
        lastName: 'Skitt',
        pic: 'https://storage.googleapis.com/hatchways-app.appspot.com/assessments/data/frontend/images/autautdeserunt.jpg',
        skill: 'Nutrition Education',
      },
    ],
  },
})